app:
  build: .
  env_file:
    - docker/.env
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www/html
    - ./docker/php.ini:/usr/local/etc/php/php.ini
    - ./docker/wp-config.php:/var/www/html/wp-config.php
mail:
  image: "mailhog/mailhog:latest"
  ports:
    - "1025:1025"
    - "8025:8025"